services:
  scanner:
    build:
      context: .
      dockerfile: packages/scanner/Dockerfile
    container_name: scanner
    restart: no
    environment:
      - MASSCAN_RATE=${MASSCAN_RATE}
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
  
  checker:
    build:
      context: .
      dockerfile: packages/checker/Dockerfile
    container_name: checker
    restart: no
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CHECK_CONCURRENCY=${CHECK_CONCURRENCY}
    depends_on:
      - db
      - redis
      - scanner
  
  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
    - ./alembic:/app/alembic
    depends_on:
      - db
  
  db:
    image: postgres:18.3-alpine
    container_name: postgres-db
    restart: no
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:8.6.2-alpine
    container_name: redis
    restart: no
    ports:
      - 6379:6379

volumes:
  pgdata: