services:
  scanner:
    build:
      context: .
      dockerfile: packages/scanner/Dockerfile
    container_name: scanner
    restart: no
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=localhost
      - DB_PORT=5432
      - MASSCAN_RATE=${MASSCAN_RATE}
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    privileged: true 
    depends_on:
      - redis
  
  porter:
    build:
      context: .
      dockerfile: packages/porter/Dockerfile
    container_name: porter
    restart: no
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=localhost
      - DB_PORT=5432
      - MASSCAN_RATE=${MASSCAN_RATE}
      - MASSCAN_RATE_TARGET=${MASSCAN_RATE_TARGET}
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - PORTER_BATCH_SIZE=${PORTER_BATCH_SIZE}
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    privileged: true 
    depends_on:
      - redis
  
  checker:
    build:
      context: .
      dockerfile: packages/checker/Dockerfile
    container_name: checker
    restart: no
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHECKER_CONCURRENCY=${CHECKER_CONCURRENCY}
      - CHECKER_PORT_CONCURRENCY=${CHECKER_PORT_CONCURRENCY}
      - SERVER_CHECK_TIMEOUT=${SERVER_CHECK_TIMEOUT}
      - S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT}
      - S3_ROOT_USER=${S3_ROOT_USER}
      - S3_ROOT_PASSWORD=${S3_ROOT_PASSWORD}
      - IPINFO_API_TOKEN=${IPINFO_API_TOKEN}
      - AIOHTTP_TIMEOUT=${AIOHTTP_TIMEOUT}
    depends_on:
      - db
      - redis
      - migrator

  monitor:
    build:
      context: .
      dockerfile: packages/monitor/Dockerfile
    container_name: monitor
    restart: no
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_CHECK_TIMEOUT=${SERVER_CHECK_TIMEOUT}
      - MONITOR_SERVER_CONCURRENCY=${MONITOR_SERVER_CONCURRENCY}
      - MONITOR_PORT_CONCURRENCY=${MONITOR_PORT_CONCURRENCY}
      - MONITOR_PLAYER_CONCURRENCY=${MONITOR_PLAYER_CONCURRENCY}
      - S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT}
      - S3_ROOT_USER=${S3_ROOT_USER}
      - S3_ROOT_PASSWORD=${S3_ROOT_PASSWORD}
      - IPINFO_API_TOKEN=${IPINFO_API_TOKEN}
      - AIOHTTP_TIMEOUT=${AIOHTTP_TIMEOUT}
      - IP_CHECK_INTERVAL_DAYS=${IP_CHECK_INTERVAL_DAYS}
      - PORTER_CHECK_INTERVAL_DAYS=${PORTER_CHECK_INTERVAL_DAYS}
    depends_on:
      - db
      - migrator
  
  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./alembic:/app/alembic
    depends_on:
      - db
  
  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - DB_HOST=db_test
      - DB_PORT=5432
      - IP_CHECK_INTERVAL_DAYS=${IP_CHECK_INTERVAL_DAYS}
      - PORTER_CHECK_INTERVAL_DAYS=${PORTER_CHECK_INTERVAL_DAYS}
    profiles:
      - manual
    depends_on:
      - db_test
  
  db_test:
    image: postgres:18.3-alpine
    container_name: postgres-db-test
    restart: no
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    profiles:
      - manual
    ports:
      - 5433:5432

  db:
    image: postgres:18.3-alpine
    container_name: postgres-db
    restart: no
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgweb:
    image: sosedoff/pgweb:0.17.0
    container_name: pgweb
    restart: no
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      - db
  
  redis:
    image: redis:8.6.2-alpine
    container_name: redis
    restart: no
    ports:
      - 6379:6379
  
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    restart: no
    environment:
      - MINIO_ROOT_USER=${S3_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${S3_ROOT_PASSWORD}
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    

volumes:
  pgdata:
  minio_data: