FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
COPY packages/common ./packages/common
RUN find . -type d \( -name tests -o -name __pycache__ \) -exec rm -rf {} +
COPY alembic ./alembic
COPY alembic.ini ./

ENV PYTHONPATH=/app/packages/common/src
ENV PATH="/app/.venv/bin:$PATH"

RUN uv sync --frozen --group migrations --no-dev
CMD ["alembic", "upgrade", "head"]