"""serversoftwaretype

Revision ID: 107eba16ef38
Revises: bf8df33c9342
Create Date: 2026-05-22 18:45:45.667900

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107eba16ef38'
down_revision: Union[str, Sequence[str], None] = 'bf8df33c9342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    
    op.drop_constraint(op.f('mods_name_key'), 'mods', type_='unique')
    op.add_column('server_port_associations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_server_ports_detected_service_type', 'server_ports', ['detected_service_type'], unique=False)
    op.create_index('ix_server_ports_protocol_type_port', 'server_ports', ['protocol_type', 'port'], unique=False)
    op.add_column('server_snapshots', sa.Column('icon', sa.String(length=32), nullable=True))
    op.drop_index(op.f('ix_server_snapshots_favicon'), table_name='server_snapshots')
    op.create_index(op.f('ix_server_snapshots_icon'), 'server_snapshots', ['icon'], unique=False)
    op.drop_column('server_snapshots', 'favicon')

    # workaround
    server_software_type = postgresql.ENUM('VANILLA', 'FORGE', 'FABRIC', 'QUILT', 'NEOFORGE', 'PAPER', 'PURPUR', 'PUFFERFISH', 'TUINITY', 'AIRPLANE', 'SPIGOT', 'CRAFTBUKKIT', 'BUKKIT', 'VELOCITY', 'WATERFALL', 'BUNGEE', 'SPONGE', 'SPONGEFORGE', 'SPONGEVANILLA', 'ARCLIGHT', 'MOHIST', 'MAGMA', 'CATSERVER', name='serversoftwaretype', create_type=False)
    server_software_type.create(op.get_bind(), checkfirst=True)
    op.alter_column('softwares', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=server_software_type,
               existing_nullable=False,
               postgresql_using="name::serversoftwaretype",
    )

    op.drop_constraint(op.f('softwares_name_key'), 'softwares', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('softwares_name_key'), 'softwares', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('softwares', 'name',
               existing_type=sa.Enum('VANILLA', 'FORGE', 'FABRIC', 'QUILT', 'NEOFORGE', 'PAPER', 'PURPUR', 'PUFFERFISH', 'TUINITY', 'AIRPLANE', 'SPIGOT', 'CRAFTBUKKIT', 'BUKKIT', 'VELOCITY', 'WATERFALL', 'BUNGEE', 'SPONGE', 'SPONGEFORGE', 'SPONGEVANILLA', 'ARCLIGHT', 'MOHIST', 'MAGMA', 'CATSERVER', name='serversoftwaretype'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.add_column('server_snapshots', sa.Column('favicon', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_server_snapshots_icon'), table_name='server_snapshots')
    op.create_index(op.f('ix_server_snapshots_favicon'), 'server_snapshots', ['favicon'], unique=False)
    op.drop_column('server_snapshots', 'icon')
    op.drop_index('ix_server_ports_protocol_type_port', table_name='server_ports')
    op.drop_index('ix_server_ports_detected_service_type', table_name='server_ports')
    op.drop_column('server_port_associations', 'created_at')
    op.create_unique_constraint(op.f('mods_name_key'), 'mods', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
