"""ipmodel is_multiport

Revision ID: 2936efdfa3c8
Revises: 42bdee635b71
Create Date: 2026-07-15 11:26:13.524290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2936efdfa3c8'
down_revision: Union[str, Sequence[str], None] = '42bdee635b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ips', sa.Column('is_multiport', sa.Boolean(), nullable=False))
    op.drop_column('servers', 'is_multiport')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('is_multiport', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('ips', 'is_multiport')
    # ### end Alembic commands ###
