"""ipmodel

Revision ID: 42bdee635b71
Revises: bc0586dcd3ea
Create Date: 2026-07-06 18:23:06.248637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42bdee635b71'
down_revision: Union[str, Sequence[str], None] = 'bc0586dcd3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('last_ip_check_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_porter_check_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('ip_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol_type', postgresql.ENUM('TCP', 'UDP', name='protocoltype', create_type=False), nullable=False),
    sa.Column('detected_service_type', postgresql.ENUM('BLUEMAP', 'DYNMAP', 'PL3XMAP', 'SQUAREMAP', 'AMP', 'PTERODACTYL', 'PELICAN', 'MULTICRAFT', 'CRAFTY', 'GENERIC_HTTP', 'UNKNOWN', name='detectedservicetype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ip_id'], ['ips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ip_ports_detected_service_type', 'ip_ports', ['detected_service_type'], unique=False)
    op.create_index(op.f('ix_ip_ports_ip_id'), 'ip_ports', ['ip_id'], unique=False)
    op.create_index('ix_ip_ports_protocol_type_port', 'ip_ports', ['protocol_type', 'port'], unique=False)
    op.drop_table('server_port_associations')
    op.drop_index(op.f('ix_server_ports_detected_service_type'), table_name='server_ports')
    op.drop_index(op.f('ix_server_ports_protocol_type_port'), table_name='server_ports')
    op.drop_table('server_ports')
    op.add_column('servers', sa.Column('ip_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_servers_ip'), table_name='servers')
    op.drop_constraint(op.f('uq_servers_ip_port'), 'servers', type_='unique')
    op.create_index(op.f('ix_servers_ip_id'), 'servers', ['ip_id'], unique=False)
    op.create_foreign_key(None, 'servers', 'ips', ['ip_id'], ['id'], ondelete='CASCADE')
    op.drop_column('servers', 'ip')
    op.drop_column('servers', 'last_seen_at')
    op.drop_column('servers', 'longitude')
    op.drop_column('servers', 'latitude')
    op.drop_column('servers', 'last_ip_check_at')
    op.drop_column('servers', 'region')
    op.drop_column('servers', 'country')
    op.drop_column('servers', 'last_porter_check_at')
    op.drop_column('servers', 'city')
    op.drop_column('servers', 'asn')
    op.drop_column('servers', 'hostname')
    op.add_column('subchunks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subchunks', 'created_at')
    op.add_column('servers', sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('asn', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('last_porter_check_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('last_ip_check_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_index(op.f('ix_servers_ip_id'), table_name='servers')
    op.create_unique_constraint(op.f('uq_servers_ip_port'), 'servers', ['ip', 'port'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_servers_ip'), 'servers', ['ip'], unique=False)
    op.drop_column('servers', 'ip_id')
    op.create_table('server_ports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protocol_type', postgresql.ENUM('TCP', 'UDP', name='protocoltype'), autoincrement=False, nullable=False),
    sa.Column('detected_service_type', postgresql.ENUM('BLUEMAP', 'DYNMAP', 'PL3XMAP', 'SQUAREMAP', 'AMP', 'PTERODACTYL', 'PELICAN', 'MULTICRAFT', 'CRAFTY', 'GENERIC_HTTP', 'UNKNOWN', name='detectedservicetype'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('server_ports_pkey'))
    )
    op.create_index(op.f('ix_server_ports_protocol_type_port'), 'server_ports', ['protocol_type', 'port'], unique=False)
    op.create_index(op.f('ix_server_ports_detected_service_type'), 'server_ports', ['detected_service_type'], unique=False)
    op.create_table('server_port_associations',
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_port_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('server_port_associations_server_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_port_id'], ['server_ports.id'], name=op.f('server_port_associations_server_port_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'server_port_id', name=op.f('server_port_associations_pkey'))
    )
    op.drop_index('ix_ip_ports_protocol_type_port', table_name='ip_ports')
    op.drop_index(op.f('ix_ip_ports_ip_id'), table_name='ip_ports')
    op.drop_index('ix_ip_ports_detected_service_type', table_name='ip_ports')
    op.drop_table('ip_ports')
    op.drop_table('ips')
    # ### end Alembic commands ###
