"""ServerPlayerAssociationModel removed

Revision ID: 48f2cd52e16d
Revises: 6b28a9af2bf7
Create Date: 2026-05-26 19:12:34.993214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f2cd52e16d'
down_revision: Union[str, Sequence[str], None] = '6b28a9af2bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
