"""last_deep_check_at changed to last_ip_check_at and last_porter_check_at

Revision ID: 5bbe39fdb13d
Revises: e417f604100f
Create Date: 2026-05-25 08:03:29.876049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bbe39fdb13d'
down_revision: Union[str, Sequence[str], None] = 'e417f604100f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('last_ip_check_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('servers', sa.Column('last_porter_check_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('servers', 'last_deep_check_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('last_deep_check_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('servers', 'last_porter_check_at')
    op.drop_column('servers', 'last_ip_check_at')
    # ### end Alembic commands ###
