"""ServerPlayerAssociationModel removed

Revision ID: 6b28a9af2bf7
Revises: 5bbe39fdb13d
Create Date: 2026-05-26 19:05:44.464762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b28a9af2bf7'
down_revision: Union[str, Sequence[str], None] = '5bbe39fdb13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_player_associations_created_at'), table_name='server_player_associations')
    op.drop_index(op.f('ix_server_player_associations_player_id'), table_name='server_player_associations')
    op.drop_table('server_player_associations')
    op.add_column('player_sessions', sa.Column('server_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_player_sessions_server_id'), 'player_sessions', ['server_id'], unique=False)
    op.create_foreign_key(None, 'player_sessions', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_player_sessions_server_id'), table_name='player_sessions')
    op.drop_column('player_sessions', 'server_id')
    op.create_table('server_player_associations',
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('server_player_associations_player_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('server_player_associations_server_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'player_id', name=op.f('server_player_associations_pkey'))
    )
    op.create_index(op.f('ix_server_player_associations_player_id'), 'server_player_associations', ['player_id'], unique=False)
    op.create_index(op.f('ix_server_player_associations_created_at'), 'server_player_associations', ['created_at'], unique=False)
    # ### end Alembic commands ###
