"""

Revision ID: 96240d4145eb
Revises: 2936efdfa3c8
Create Date: 2026-08-12 08:06:35.344537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96240d4145eb'
down_revision: Union[str, Sequence[str], None] = '2936efdfa3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('last_bot_check_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'last_bot_check_at')
    # ### end Alembic commands ###
