"""ip are strings in db now

Revision ID: 99652e41eb50
Revises: 48f2cd52e16d
Create Date: 2026-06-04 14:26:15.442569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99652e41eb50'
down_revision: Union[str, Sequence[str], None] = '48f2cd52e16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'ip',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'ip',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=False)
    # ### end Alembic commands ###
