"""new idices

Revision ID: bc0586dcd3ea
Revises: 99652e41eb50
Create Date: 2026-06-07 12:21:23.257346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc0586dcd3ea'
down_revision: Union[str, Sequence[str], None] = '99652e41eb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_player_sessions_player_id_from_desc', 'player_sessions', ['player_id', sa.literal_column('from_ DESC')], unique=False)
    op.create_index('ix_player_sessions_server_id_from_desc', 'player_sessions', ['server_id', sa.literal_column('from_ DESC')], unique=False)
    op.drop_index(op.f('ix_player_snapshots_created_at'), table_name='player_snapshots')
    op.create_index('ix_player_snapshots_player_id_created_at', 'player_snapshots', ['player_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_server_bot_snapshots_server_id_created_at'), table_name='server_bot_snapshots')
    op.create_index('ix_server_bot_snapshots_server_id_created_at', 'server_bot_snapshots', ['server_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_server_dynamic_snapshots_server_id_created_at'), table_name='server_dynamic_snapshots')
    op.create_index('ix_server_dynamic_snapshots_server_id_created_at', 'server_dynamic_snapshots', ['server_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_server_sessions_server_id_from_desc', 'server_sessions', ['server_id', sa.literal_column('from_ DESC')], unique=False)
    op.drop_index(op.f('ix_server_snapshots_server_id_created_at'), table_name='server_snapshots')
    op.create_index('ix_server_snapshots_server_id_created_at', 'server_snapshots', ['server_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_unique_constraint('uq_servers_ip_port', 'servers', ['ip', 'port'])
    op.drop_column('subchunks', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subchunks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_servers_ip_port', 'servers', type_='unique')
    op.drop_index('ix_server_snapshots_server_id_created_at', table_name='server_snapshots')
    op.create_index(op.f('ix_server_snapshots_server_id_created_at'), 'server_snapshots', ['server_id', 'created_at'], unique=False)
    op.drop_index('ix_server_sessions_server_id_from_desc', table_name='server_sessions')
    op.drop_index('ix_server_dynamic_snapshots_server_id_created_at', table_name='server_dynamic_snapshots')
    op.create_index(op.f('ix_server_dynamic_snapshots_server_id_created_at'), 'server_dynamic_snapshots', ['server_id', 'created_at'], unique=False)
    op.drop_index('ix_server_bot_snapshots_server_id_created_at', table_name='server_bot_snapshots')
    op.create_index(op.f('ix_server_bot_snapshots_server_id_created_at'), 'server_bot_snapshots', ['server_id', 'created_at'], unique=False)
    op.drop_index('ix_player_snapshots_player_id_created_at', table_name='player_snapshots')
    op.create_index(op.f('ix_player_snapshots_created_at'), 'player_snapshots', ['created_at'], unique=False)
    op.drop_index('ix_player_sessions_server_id_from_desc', table_name='player_sessions')
    op.drop_index('ix_player_sessions_player_id_from_desc', table_name='player_sessions')
    # ### end Alembic commands ###
