"""new models

Revision ID: dcea49b1951b
Revises: 7e6878f653af
Create Date: 2026-05-10 07:48:33.396603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcea49b1951b'
down_revision: Union[str, Sequence[str], None] = '7e6878f653af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_mods_name', 'mods', ['name'], unique=False)
    op.create_index('ix_mods_name_version', 'mods', ['name', 'version'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_type', sa.Enum('PREMIUM', 'OFFLINE', 'BEDROCK', name='playertype'), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_players_created_at', 'players', ['created_at'], unique=False)
    op.create_index('ix_players_player_type', 'players', ['player_type'], unique=False)
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_plugins_name', 'plugins', ['name'], unique=False)
    op.create_table('resource_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('server_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol_type', sa.Enum('TCP', 'UDP', name='protocoltype'), nullable=False),
    sa.Column('detected_service_type', sa.Enum('BLUEMAP', 'DYNMAP', 'PL3XMAP', 'SQUAREMAP', 'AMP', 'PTERODACTYL', 'PELICAN', 'MULTICRAFT', 'CRAFTY', 'GENERIC_HTTP', 'UNKNOWN', name='detectedservicetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('softwares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_softwares_name', 'softwares', ['name'], unique=False)
    op.create_index('ix_softwares_version', 'softwares', ['version'], unique=False)
    op.create_table('player_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('from_', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_sessions_player_id'), 'player_sessions', ['player_id'], unique=False)
    op.create_table('player_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('skin', sa.String(length=32), nullable=True),
    sa.Column('cape', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_snapshots_created_at', 'player_snapshots', ['created_at'], unique=False)
    op.create_index('ix_player_snapshots_name', 'player_snapshots', ['name'], unique=False)
    op.create_index(op.f('ix_player_snapshots_player_id'), 'player_snapshots', ['player_id'], unique=False)
    op.create_table('server_bot_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_bot_snapshots_server_id'), 'server_bot_snapshots', ['server_id'], unique=False)
    op.create_index('ix_server_bot_snapshots_server_id_created_at', 'server_bot_snapshots', ['server_id', 'created_at'], unique=False)
    op.create_table('server_dynamic_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('players_online', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_server_dynamic_snapshots_players_online', 'server_dynamic_snapshots', ['players_online'], unique=False)
    op.create_index(op.f('ix_server_dynamic_snapshots_server_id'), 'server_dynamic_snapshots', ['server_id'], unique=False)
    op.create_index('ix_server_dynamic_snapshots_server_id_created_at', 'server_dynamic_snapshots', ['server_id', 'created_at'], unique=False)
    op.create_table('server_player_associations',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'player_id')
    )
    op.create_index('ix_server_player_associations_created_at', 'server_player_associations', ['created_at'], unique=False)
    op.create_index('ix_server_player_associations_player_id', 'server_player_associations', ['player_id'], unique=False)
    op.create_table('server_port_associations',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('server_port_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_port_id'], ['server_ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'server_port_id')
    )
    op.create_table('server_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('from_', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_sessions_server_id'), 'server_sessions', ['server_id'], unique=False)
    op.create_table('server_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('players_max', sa.Integer(), nullable=False),
    sa.Column('motd', sa.String(length=512), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('protocol', sa.Integer(), nullable=True),
    sa.Column('favicon', sa.String(length=32), nullable=True),
    sa.Column('enforcesSecureChat', sa.Boolean(), nullable=True),
    sa.Column('fml_network_version', sa.Integer(), nullable=True),
    sa.Column('mods_truncated', sa.Boolean(), nullable=True),
    sa.Column('map_name', sa.String(length=64), nullable=True),
    sa.Column('gamemode', sa.String(length=32), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_id'], ['softwares.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_snapshots_favicon'), 'server_snapshots', ['favicon'], unique=False)
    op.create_index('ix_server_snapshots_players_max', 'server_snapshots', ['players_max'], unique=False)
    op.create_index(op.f('ix_server_snapshots_server_id'), 'server_snapshots', ['server_id'], unique=False)
    op.create_index('ix_server_snapshots_server_id_created_at', 'server_snapshots', ['server_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_server_snapshots_software_id'), 'server_snapshots', ['software_id'], unique=False)
    op.create_index('ix_server_snapshots_version', 'server_snapshots', ['version'], unique=False)
    op.create_table('server_bot_snapshot_mod_associations',
    sa.Column('bot_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_snapshot_id'], ['server_bot_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bot_snapshot_id', 'mod_id')
    )
    op.create_index('ix_bot_mod_mod_id', 'server_bot_snapshot_mod_associations', ['mod_id'], unique=False)
    op.create_index('ix_bot_mod_snapshot_id', 'server_bot_snapshot_mod_associations', ['bot_snapshot_id'], unique=False)
    op.create_table('server_bot_snapshot_resource_pack_associations',
    sa.Column('bot_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('resource_pack_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_snapshot_id'], ['server_bot_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_pack_id'], ['resource_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bot_snapshot_id', 'resource_pack_id')
    )
    op.create_index('ix_bot_rp_pack_id', 'server_bot_snapshot_resource_pack_associations', ['resource_pack_id'], unique=False)
    op.create_index('ix_bot_rp_snapshot_id', 'server_bot_snapshot_resource_pack_associations', ['bot_snapshot_id'], unique=False)
    op.create_table('server_snapshot_mod_associations',
    sa.Column('server_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_snapshot_id'], ['server_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_snapshot_id', 'mod_id')
    )
    op.create_index('ix_ss_mod_mod_id', 'server_snapshot_mod_associations', ['mod_id'], unique=False)
    op.create_index('ix_ss_mod_snapshot_id', 'server_snapshot_mod_associations', ['server_snapshot_id'], unique=False)
    op.create_table('server_snapshot_plugin_associations',
    sa.Column('server_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_snapshot_id'], ['server_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_snapshot_id', 'plugin_id')
    )
    op.create_index('ix_ss_plugin_plugin_id', 'server_snapshot_plugin_associations', ['plugin_id'], unique=False)
    op.create_index('ix_ss_plugin_snapshot_id', 'server_snapshot_plugin_associations', ['server_snapshot_id'], unique=False)
    op.create_table('subchunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_snapshot_id'], ['server_bot_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subchunks_bot_snapshot_id'), 'subchunks', ['bot_snapshot_id'], unique=False)
    op.create_index(op.f('ix_subchunks_hash'), 'subchunks', ['hash'], unique=False)
    op.add_column('servers', sa.Column('is_lan', sa.Boolean(), nullable=False))
    op.add_column('servers', sa.Column('is_multiport', sa.Boolean(), nullable=False))

    
    
    # workaround
    server_type = postgresql.ENUM('LEGACY', 'JAVA', 'BEDROCK', name='servertype', create_type=False)
    server_type.create(op.get_bind(), checkfirst=True)
    op.add_column('servers', sa.Column('server_type', server_type, nullable=False))

    

    op.add_column('servers', sa.Column('last_deep_check_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('servers', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('servers', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('servers', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('servers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('servers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('servers', sa.Column('hostname', sa.String(length=255), nullable=True))
    op.add_column('servers', sa.Column('asn', sa.String(length=150), nullable=True))
    op.add_column('servers', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_servers_created_at', 'servers', ['created_at'], unique=False)
    op.create_index('ix_servers_ip', 'servers', ['ip'], unique=False)
    op.create_index('ix_servers_port', 'servers', ['port'], unique=False)
    op.create_index('ix_servers_server_type', 'servers', ['server_type'], unique=False)
    op.drop_column('servers', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('ix_servers_server_type', table_name='servers')
    op.drop_index('ix_servers_port', table_name='servers')
    op.drop_index('ix_servers_ip', table_name='servers')
    op.drop_index('ix_servers_created_at', table_name='servers')
    op.drop_column('servers', 'last_seen_at')
    op.drop_column('servers', 'asn')
    op.drop_column('servers', 'hostname')
    op.drop_column('servers', 'longitude')
    op.drop_column('servers', 'latitude')
    op.drop_column('servers', 'city')
    op.drop_column('servers', 'region')
    op.drop_column('servers', 'country')
    op.drop_column('servers', 'last_deep_check_at')
    op.drop_column('servers', 'server_type')
    op.drop_column('servers', 'is_multiport')
    op.drop_column('servers', 'is_lan')
    op.drop_index(op.f('ix_subchunks_hash'), table_name='subchunks')
    op.drop_index(op.f('ix_subchunks_bot_snapshot_id'), table_name='subchunks')
    op.drop_table('subchunks')
    op.drop_index('ix_ss_plugin_snapshot_id', table_name='server_snapshot_plugin_associations')
    op.drop_index('ix_ss_plugin_plugin_id', table_name='server_snapshot_plugin_associations')
    op.drop_table('server_snapshot_plugin_associations')
    op.drop_index('ix_ss_mod_snapshot_id', table_name='server_snapshot_mod_associations')
    op.drop_index('ix_ss_mod_mod_id', table_name='server_snapshot_mod_associations')
    op.drop_table('server_snapshot_mod_associations')
    op.drop_index('ix_bot_rp_snapshot_id', table_name='server_bot_snapshot_resource_pack_associations')
    op.drop_index('ix_bot_rp_pack_id', table_name='server_bot_snapshot_resource_pack_associations')
    op.drop_table('server_bot_snapshot_resource_pack_associations')
    op.drop_index('ix_bot_mod_snapshot_id', table_name='server_bot_snapshot_mod_associations')
    op.drop_index('ix_bot_mod_mod_id', table_name='server_bot_snapshot_mod_associations')
    op.drop_table('server_bot_snapshot_mod_associations')
    op.drop_index('ix_server_snapshots_version', table_name='server_snapshots')
    op.drop_index(op.f('ix_server_snapshots_software_id'), table_name='server_snapshots')
    op.drop_index('ix_server_snapshots_server_id_created_at', table_name='server_snapshots')
    op.drop_index(op.f('ix_server_snapshots_server_id'), table_name='server_snapshots')
    op.drop_index('ix_server_snapshots_players_max', table_name='server_snapshots')
    op.drop_index(op.f('ix_server_snapshots_favicon'), table_name='server_snapshots')
    op.drop_table('server_snapshots')
    op.drop_index(op.f('ix_server_sessions_server_id'), table_name='server_sessions')
    op.drop_table('server_sessions')
    op.drop_table('server_port_associations')
    op.drop_index('ix_server_player_associations_player_id', table_name='server_player_associations')
    op.drop_index('ix_server_player_associations_created_at', table_name='server_player_associations')
    op.drop_table('server_player_associations')
    op.drop_index('ix_server_dynamic_snapshots_server_id_created_at', table_name='server_dynamic_snapshots')
    op.drop_index(op.f('ix_server_dynamic_snapshots_server_id'), table_name='server_dynamic_snapshots')
    op.drop_index('ix_server_dynamic_snapshots_players_online', table_name='server_dynamic_snapshots')
    op.drop_table('server_dynamic_snapshots')
    op.drop_index('ix_server_bot_snapshots_server_id_created_at', table_name='server_bot_snapshots')
    op.drop_index(op.f('ix_server_bot_snapshots_server_id'), table_name='server_bot_snapshots')
    op.drop_table('server_bot_snapshots')
    op.drop_index(op.f('ix_player_snapshots_player_id'), table_name='player_snapshots')
    op.drop_index('ix_player_snapshots_name', table_name='player_snapshots')
    op.drop_index('ix_player_snapshots_created_at', table_name='player_snapshots')
    op.drop_table('player_snapshots')
    op.drop_index(op.f('ix_player_sessions_player_id'), table_name='player_sessions')
    op.drop_table('player_sessions')
    op.drop_index('ix_softwares_version', table_name='softwares')
    op.drop_index('ix_softwares_name', table_name='softwares')
    op.drop_table('softwares')
    op.drop_table('server_ports')
    op.drop_table('resource_packs')
    op.drop_index('ix_plugins_name', table_name='plugins')
    op.drop_table('plugins')
    op.drop_index('ix_players_player_type', table_name='players')
    op.drop_index('ix_players_created_at', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_mods_name_version', table_name='mods')
    op.drop_index('ix_mods_name', table_name='mods')
    op.drop_table('mods')
    # ### end Alembic commands ###
